from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate submission paper figures from real tables.")
    parser.add_argument("--tables_dir", default="outputs/paper_tables_submission")
    parser.add_argument("--output_dir", default="outputs/paper_figures_submission")
    parser.add_argument("--paper_figures_dir", default="paper/figures")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    tables_dir = Path(args.tables_dir)
    output_dir = Path(args.output_dir)
    paper_dir = Path(args.paper_figures_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paper_dir.mkdir(parents=True, exist_ok=True)
    skipped: list[str] = []
    _figure1(output_dir)
    _figure2(output_dir)
    _figure3(tables_dir, output_dir, skipped)
    _figure4(tables_dir, output_dir, skipped)
    _figure5(tables_dir, output_dir, skipped)
    _figure6(tables_dir, output_dir, skipped)
    _figure8(tables_dir, output_dir, skipped)
    skipped.append("fig_evidence_chain_case: requires a real case with routing weights and rationale; not generated by default.")
    for path in output_dir.glob("*.pdf"):
        shutil.copyfile(path, paper_dir / path.name)
    for path in output_dir.glob("*.png"):
        shutil.copyfile(path, paper_dir / path.name)
    (output_dir / "skipped_figures_report.md").write_text("\n".join(f"- {item}" for item in skipped) + "\n", encoding="utf-8")
    print(f"Wrote figures to {output_dir}; copied available figures to {paper_dir}")


def _figure1(output_dir: Path) -> None:
    labels = ["risk-relevant", "irrelevant/noisy"]
    values = [906, 3254]
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.2))
    axes[0].pie(values, labels=labels, autopct="%1.1f%%", startangle=90, wedgeprops={"width": 0.42})
    axes[0].set_title("Risk-card relevance")
    case_labels = ["C1\nbehavioral\ncontradiction", "C2\ncounterparty\nrisk", "C3\nirrelevant\nheterophily"]
    axes[1].bar(case_labels, [1, 1, 1], color=["#4c78a8", "#72b7b2", "#bab0ac"])
    axes[1].set_ylim(0, 1.25)
    axes[1].set_yticks([])
    axes[1].set_title("Representative cases")
    _save(fig, output_dir, "fig_motivating_observation")


def _figure2(output_dir: Path) -> None:
    steps = [
        "Input graph",
        "Candidate retrieval",
        "Risk card builder",
        "LLM annotation",
        "Risk-relevant filter",
        "Dual-branch encoder",
        "Fraud prediction",
        "Top evidence chains",
    ]
    fig, ax = plt.subplots(figsize=(10, 2.7))
    ax.axis("off")
    for idx, step in enumerate(steps):
        x = idx / max(len(steps) - 1, 1)
        ax.text(x, 0.55, step, ha="center", va="center", fontsize=8, bbox={"boxstyle": "round,pad=0.35", "fc": "white", "ec": "#4c78a8"})
        if idx < len(steps) - 1:
            ax.annotate("", xy=((idx + 0.72) / (len(steps) - 1), 0.55), xytext=((idx + 0.28) / (len(steps) - 1), 0.55), arrowprops={"arrowstyle": "->", "lw": 1.2})
    ax.set_title("HERO-GNN framework", fontsize=11)
    _save(fig, output_dir, "fig_framework_hero_gnn")


def _figure3(tables_dir: Path, output_dir: Path, skipped: list[str]) -> None:
    table = _read_table(tables_dir / "table_text_rich_main.csv")
    methods = ["graphsage", "care_gnn", "graphconsis", "dgp", "mled", "hero_gnn"]
    if table.empty or not _has_methods(table, methods):
        skipped.append("fig_main_results_bar: missing text-rich main results for required methods.")
        return
    if pd.to_numeric(table[table["model"].isin(methods)]["AUPRC_mean"], errors="coerce").dropna().empty:
        skipped.append("fig_main_results_bar: required methods exist but metrics are NA.")
        return
    _grouped_bar(table, methods, "AUPRC_mean", output_dir, "fig_main_results_bar", "Text-rich AUPRC")


def _figure4(tables_dir: Path, output_dir: Path, skipped: list[str]) -> None:
    table = _read_table(tables_dir / "table_ablation.csv")
    if table.empty or "AUPRC_mean" not in table:
        skipped.append("fig_ablation_drop_bar: missing ablation table.")
        return
    hero = table[table["model"].astype(str).isin(["hero_gnn", "HERO-GNN"])]
    if hero.empty:
        skipped.append("fig_ablation_drop_bar: missing HERO-GNN reference.")
        return
    ref = float(pd.to_numeric(hero.iloc[0].get("AUPRC_mean"), errors="coerce"))
    values = ref - pd.to_numeric(table["AUPRC_mean"], errors="coerce")
    fig, ax = plt.subplots(figsize=(7, 3.4))
    ax.bar(table["model"].astype(str), values)
    ax.set_ylabel("AUPRC drop")
    ax.tick_params(axis="x", rotation=25)
    _save(fig, output_dir, "fig_ablation_drop_bar")


def _figure5(tables_dir: Path, output_dir: Path, skipped: list[str]) -> None:
    table = _read_table(tables_dir / "table_llm_coverage_sensitivity.csv")
    if table.empty or "coverage" not in table:
        skipped.append("fig_llm_coverage_curve: missing LLM coverage table.")
        return
    fig, ax = plt.subplots(figsize=(5.8, 3.4))
    for metric in ["Macro-F1_mean", "AUROC_mean", "AUPRC_mean"]:
        if metric in table:
            ax.plot(pd.to_numeric(table["coverage"], errors="coerce"), pd.to_numeric(table[metric], errors="coerce"), marker="o", label=metric.replace("_mean", ""))
    ax.set_xlabel("Qwen coverage")
    ax.set_ylabel("Score")
    ax.legend(frameon=False)
    _save(fig, output_dir, "fig_llm_coverage_curve")


def _figure6(tables_dir: Path, output_dir: Path, skipped: list[str]) -> None:
    table = _read_table(tables_dir / "table_transaction_benchmark.csv")
    methods = ["graphsage", "bwgnn", "linkx", "hogrl", "rgtan", "hero_official"]
    if table.empty or not _has_methods(table, methods):
        skipped.append("fig_transaction_results_dotplot: missing Elliptic transaction results.")
        return
    subset = table[table["model"].isin(methods)].copy()
    subset["AUPRC_mean"] = pd.to_numeric(subset["AUPRC_mean"], errors="coerce")
    if subset["AUPRC_mean"].dropna().empty:
        skipped.append("fig_transaction_results_dotplot: Elliptic methods exist but metrics are NA.")
        return
    fig, ax = plt.subplots(figsize=(5.8, 3.6))
    ax.scatter(subset["AUPRC_mean"], subset["model"])
    ax.set_xlabel("AUPRC")
    _save(fig, output_dir, "fig_transaction_results_dotplot")


def _figure8(tables_dir: Path, output_dir: Path, skipped: list[str]) -> None:
    table = _read_table(tables_dir / "table_text_rich_main.csv")
    methods = ["dgp", "mled", "care_gnn", "graphconsis", "hero_gnn"]
    if table.empty or not _has_methods(table, methods):
        skipped.append("fig_seed_stability_pointplot: missing 5-seed main results.")
        return
    subset = table[table["model"].isin(methods)].copy()
    if pd.to_numeric(subset["AUPRC_mean"], errors="coerce").dropna().empty:
        skipped.append("fig_seed_stability_pointplot: methods exist but metrics are NA.")
        return
    fig, ax = plt.subplots(figsize=(6.2, 3.6))
    x = np.arange(subset.shape[0])
    means = pd.to_numeric(subset["AUPRC_mean"], errors="coerce")
    stds = pd.to_numeric(subset["AUPRC_std"], errors="coerce").fillna(0.0)
    ax.errorbar(x, means, yerr=stds, fmt="o", capsize=4)
    ax.set_xticks(x, subset["model"], rotation=25, ha="right")
    ax.set_ylabel("AUPRC mean +/- std")
    _save(fig, output_dir, "fig_seed_stability_pointplot")


def _grouped_bar(table: pd.DataFrame, methods: list[str], metric: str, output_dir: Path, stem: str, title: str) -> None:
    datasets = list(dict.fromkeys(table["dataset"].astype(str).tolist()))
    x = np.arange(len(datasets))
    width = 0.12
    fig, ax = plt.subplots(figsize=(8.2, 3.6))
    for idx, method in enumerate(methods):
        values = []
        for dataset in datasets:
            row = table[(table["dataset"] == dataset) & (table["model"] == method)]
            values.append(float(pd.to_numeric(row.iloc[0][metric], errors="coerce")) if not row.empty else np.nan)
        ax.bar(x + (idx - len(methods) / 2) * width, values, width=width, label=method)
    if table[table["model"].isin(methods)][metric].pipe(pd.to_numeric, errors="coerce").dropna().empty:
        plt.close(fig)
        return
    ax.set_xticks(x, datasets)
    ax.set_ylabel(metric.replace("_mean", ""))
    ax.set_title(title)
    ax.legend(frameon=False, ncol=3, fontsize=8)
    _save(fig, output_dir, stem)


def _read_table(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def _has_methods(table: pd.DataFrame, methods: list[str]) -> bool:
    if "model" not in table:
        return False
    present = set(table["model"].dropna().astype(str))
    return set(methods).issubset(present)


def _save(fig, output_dir: Path, stem: str) -> None:
    fig.tight_layout()
    fig.savefig(output_dir / f"{stem}.pdf")
    fig.savefig(output_dir / f"{stem}.png", dpi=220)
    plt.close(fig)


if __name__ == "__main__":
    main()
